package com.mj.report.dao;

import java.util.List;
import java.util.Map;

import com.mj.report.model.ImportRecord;
import com.mj.report.model.User;

/**
 * excel导入记录
 *@ClassName:ImportRecordDao.java
 *@author MJ009
 *@date 2016年9月13日
 *@Description TODO
 *
 */
public interface ImportRecordDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_record
     *
     * @mbggenerated
     */
    int insert(ImportRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_record
     *
     * @mbggenerated
     */
    int insertSelective(ImportRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_record
     *
     * @mbggenerated
     */
    ImportRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImportRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table import_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImportRecord record);
    
    /**
     * 根据用户名查询，status = 0 正在解析中的记录
     * dataType 数据类型
     * @return
     */
    ImportRecord findRec(String dataType);
    
    /**
     * 导入记录
     * @return
     */
    List<ImportRecord> iRecordList();
    
    /**
	 * 记录总数
	 * 
	 * @return
	 */
	@SuppressWarnings("rawtypes")
	int countIRecord( Map map);
	
	/**
	 * 导入列表
	 * @param map
	 * @return
	 */
	@SuppressWarnings("rawtypes")
	List<ImportRecord> findAllIRecord(Map map);
    
}